name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for telling me an issue! I will try to make that issue same result and I will fix it! Wait for me to respond back!'
        pr-message: 'Thank you for improving the module to be better! Now you just need to wait until I was reviewing your pull request! Hope your pull request good enough to merge!'
